### ISSUE TITLE
netflix and prime as scraping sources 

### ISSUE THREAD

**Issue by ruegnueg** [Wilson-Magic/repository.magicality#3]
hi,

would it be possible to add netflix and prime as scraping sources. a fork called lastship does that. sadly the addon is for German sources only.

so on leia, with prime and / or netflix addon installed it can play directly those addons.

it's a really great feature. 
And the german soruces should be updated, Theyre all outdated in ALL english addons :)
like serienstream.to etc :) They work in lastship, specialiced for german sources, but in no other addon like yours or yoda or whatever :)

A man can dream can he ;)

**Comment by Wilson-Magic** [comment]
Magicality is depreciated now. Sorry.

**Comment by ruegnueg** [comment]
yeah I heard. Will you continue Masterani?

**Comment by Wilson-Magic** [comment]
Yes, but tbh I haven't been doing much recently.

**Comment by ruegnueg** [comment]
It works just fine so you don't have to. But if something happens it's good to know its not abbandonend 😉
