### ISSUE TITLE
Dramatic Add

### ISSUE THREAD

**Issue by nexus667** [Wilson-Magic/repository.magicality#7]
Is the Dramatic addon coming back?

**Comment by Wilson-Magic** [comment]
I'm doing other things for now but there is a chance it will in the future. Stay tuned for now.

**Comment by Wilson-Magic** [comment]
For now I will put this here.

https://drive.google.com/file/d/104-62EaBufsCVMFbtcTCWAAvcqB-n7BZ/view?usp=sharing

Download this on a pc and install on your kodi setup. Sorry for the inconvienience.
